name: 'Diff tracer'
description: 'Diff tracer'
author: 'Diff tracer team'

# Define your inputs here.
inputs: {}

# Define your outputs here.
outputs:
  skip:
    description: 'Whether the remainder of the job can be skipped'

runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
  post-if: success()
